### ISSUE TITLE
No demo on theme site

### ISSUE THREAD

**Issue by digitalcraftsman** [aerohub/hugrid#1]
Hello @aerohub,

could you add a folder named `static` to the `exampleSite` directory? Otherwise the build script of the theme site isn't able to generate a demo for your theme.

Thanks

**Comment by aerohub** [comment]
Hello @digitalcraftsman,

Done! 

Thanks!

**Comment by digitalcraftsman** [comment]
Great. The demo should appear with the next update of the theme list.
