### ISSUE TITLE
new box-grid

### ISSUE THREAD

**Issue by Karolinehc** [aerohub/hugrid#14]
Hello there @aerohub  :) please Can you tell me what I must type on the command line windows to appear a new box or grid? I have added it on the configuration items tolm a new "items" but it hasn't worked, Any indication would be appreciated

**Comment by aerohub** [comment]
Hello, @Karolinehc You have to copy exampleSite folder content to your project root. Then fill file `data/items.toml` with your data. You may delete unnecessary example items and add yours according this structure:
```
[[items]]
title = "..."                                # title of your box
image = "images/full/..."                    # full image url
thumb = "images/thumbs/..."                  # thumbnail url
alt = "..."                                  # alt attribute for image
description = "..."                          # short text description
url = "..."                                  # button url
```
And then run `hugo server -w` on commandline to see your grid in action. When your grid is ready run `hugo` to build everything. Youl find your grid files in `public` folder in the root of your project

**Comment by Karolinehc** [comment]
Thank you very much, @aerohub  I will follow your advice :) if I have another question I will ask you.
