### ISSUE TITLE
[Feature Requests] some blogish features

### ISSUE THREAD

**Issue by marteaurouge** [aerohub/hugrid#2]
Hey love the theme, it's really fresh and interesting, i feel some parts are missing like:
- direct links to post(s)
- tag support
- pagination

etc,

besides that the concept is amazing, works well on destop and phones/tablets

**Comment by aerohub** [comment]
Hello, @marteaurouge 
Sincerely speaking, this theme (I think it's not even a theme, just a page with some placeholders) was never supposed for blogging. I've ported it for a page with contacts. There are no styles for rich text, no layouts and no desire to write them. Choose from many great  blogging themes [here](http://themes.gohugo.io/), please, or fork this repository and do it yourself! You are right, concept is good, well, everything is in your hands:)

**Comment by marteaurouge** [comment]
okay :) thanks for sharing this btw!

**Comment by jazzi** [comment]
From 0.4.2 Hugo introduces [Theme Components](https://gohugo.io/themes/theme-components/), maybe can combine this theme Hugrid with other blogging theme, what do you think? @aerohub @marteaurouge
